name: pullImage
on: 
   
    workflow_dispatch:  

jobs:
    echo:
        runs-on: self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Run New Container
              run: |
                docker pull edwinasweeney/modelbuild:latest
               
                
               
           

